export { bind } from './bind.js'
export { call, apply } from './call.js'
export { compose } from './compose.js'
export { create } from './create.js'
export { curry } from './curry.js'
export { debounceTail, debounceHead } from './debounce.js'
export { deepClone } from './deepClone.js'
export { flatArray } from './flat.js'
export { inherit } from './inherit.js'
export { myinstanceof } from './instanceof.js'
export { mynew } from './new.js'
export { run } from './run.js'
export { throttle } from './throttle.js'
export { unique } from './unique.js'
export { map, reduce, filter } from './transform.js'
